package co.com.powersoft.learningenglish.bean;


import java.util.Map;

/**
 * Lesson generated by hbm2java
 */
public class QuestionMultichoice  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
     
     private Question exam;
     private Map<String, String>options;

    public QuestionMultichoice() {
    }

    public QuestionMultichoice(Question exam, Map<String, String> options) {
        this.exam = exam;
        this.options = options;
    }

    public Question getExam() {
        return exam;
    }

    public void setExam(Question exam) {
        this.exam = exam;
    }

    public Map<String, String> getOptions() {
        return options;
    }

    public void setOptions(Map<String, String> options) {
        this.options = options;
    }
     
    
    

}


