package co.com.powersoft.learningenglish.bean;


import java.util.List;

/**
 * Lesson generated by hbm2java
 */
public class QuestionMultichoice  implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
     
     private Question question;
     private List<Option> options;

    public QuestionMultichoice() {
    }

    public QuestionMultichoice(Question question, List<Option> options) {
        this.question = question;
        this.options = options;
    }

    public Question getQuestion() {
        return question;
    }

    public void setQuestion(Question question) {
        this.question = question;
    }

    public List<Option> getOptions() {
        return options;
    }

    public void setOptions(List<Option> options) {
        this.options = options;
    }
     
    
    

}


