package co.com.powersoft.learningenglish.bean;



/**
 * Lesson generated by hbm2java
 */
public class Question  implements java.io.Serializable {
    
    private static final long serialVersionUID = 1L;

    private int idQuestion;
    private String questionText;
    private String questionAudio;
    private String answer;
    private String check;

    public Question() {
    }

    public Question(int idQuestion, String questionText, String questionAudio, String answer, String check) {
        this.idQuestion = idQuestion;
        this.questionText = questionText;
        this.questionAudio = questionAudio;
        this.answer = answer;
        this.check = check;
    }    

    public int getIdQuestion() {
        return idQuestion;
    }

    public void setIdQuestion(int idQuestion) {
        this.idQuestion = idQuestion;
    }

    public String getQuestionText() {
        return questionText;
    }

    public void setQuestionText(String questionText) {
        this.questionText = questionText;
    }

    public String getQuestionAudio() {
        return questionAudio;
    }

    public void setQuestionAudio(String questionAudio) {
        this.questionAudio = questionAudio;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public String getCheck() {
        return check;
    }

    public void setCheck(String check) {
        this.check = check;
    }
    

}


