package co.com.powersoft.learningenglish.bean;



/**
 * Lesson generated by hbm2java
 */
public class Question  implements java.io.Serializable {
    
    private static final long serialVersionUID = 1L;

    private int idQuestion;
    private String question;
    private String answer;
    private String check;

    public Question() {
    }

    public Question(int idQuestion, String question, String answer, String check) {
        this.idQuestion = idQuestion;
        this.question = question;
        this.answer = answer;
        this.check = check;
    }    

    public int getIdQuestion() {
        return idQuestion;
    }

    public void setIdQuestion(int idQuestion) {
        this.idQuestion = idQuestion;
    }

    public String getQuestion() {
        return question;
    }

    public void setQuestion(String question) {
        this.question = question;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public String getCheck() {
        return check;
    }

    public void setCheck(String check) {
        this.check = check;
    }
    

}


