/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.com.powersoft.logger.constants;

/**
 * Contantes de los metodos generales
 * @author Leonardo
 * @since 2016-02-19
 */
public class OperationConstants {
    
    // <editor-fold defaultstate="collapsed" desc="TRANSACTION MANAGER GENERAL">
    
    //Ciudad
    public static final String OBTENER_CIUDADES = "OBTENER_CIUDADES";
    
    //Departamento
    public static final String OBTENER_DEPARTAMENTOS = "OBTENER_DEPARTAMENTOS";
    
    //Pais
    public static final String OBTENER_PAISES = "OBTENER_PAISES";
    
    //TipoDocumento
    public static final String OBTENER_TIPO_DOCUMENTOS = "OBTENER_TIPO_DOCUMENTOS";
        
    //Usuario
    public static final String OBTENER_USUARIO = "OBTENER_USUARIO";
    public static final String ACTUALIZAR_FECHA_ULTIMO_ACCESO = "ACTUALIZAR_FECHA_ULTIMO_ACCESO";
    
    //AccesoUsuario
    public static final String OBTENER_ACCESOS_USUARIO = "OBTENER_ACCESOS_USUARIO";
    
    //Rol
    public static final String OBTENER_ACCESO_MODULOS_SOFTWARE = "OBTENER_ACCESO_MODULOS_SOFTWARE";
    public static final String OBTENER_PERMISOS_MODULO = "OBTENER_PERMISOS_MODULO";
    
    //PersonaGeneral
    public static final String OBTENER_PERSONA_GENERAL = "OBTENER_PERSONA_GENERAL";
    public static final String OBTENER_PERSONA_GENERAL_BATCH = "OBTENER_PERSONA_GENERAL_BATCH";
    public static final String OBTENER_ID_PERSONA_GENERAL_BATCH = "OBTENER_ID_PERSONA_GENERAL_BATCH";
    public static final String AGREGAR_PERSONA_GENERAL = "AGREGAR_PERSONA_GENERAL";
    public static final String MODIFICAR_PERSONA_GENERAL = "MODIFICAR_PERSONA_GENERAL";
    public static final String ELIMINAR_PERSONA_GENERAL = "ELIMINAR_PERSONA_GENERAL";
    public static final String AUDITORIA_ELIMINAR_PERSONA_GENERAL = "AUDITORIA_ELIMINAR_PERSONA_GENERAL";
    
    //TipoActividadEconomica
    public static final String OBTENER_TIPO_ACTIVIDAD_ECONOMICA = "OBTENER_TIPO_ACTIVIDAD_ECONOMICA";
    
    //PrioridadGeneral
    public static final String OBTENER_NIVELES_PRIORIDAD = "OBTENER_NIVELES_PRIORIDAD";
    
    //SectorGeneral
    public static final String OBTENER_SECTORES_GENERAL = "OBTENER_SECTORES_GENERAL";
    
    // </editor-fold> 
    
    // <editor-fold defaultstate="collapsed" desc="TRANSACTION MANAGER LABORATORIO">
    
    //PlantaGeneral
    public static final String OBTENER_CANTIDAD_PLANTAS = "OBTENER_CANTIDAD_PLANTAS";
    public static final String CARGAR_PLANTAS = "CARGAR_PLANTAS";
    public static final String OBTENER_PLANTA_GENERAL = "OBTENER_PLANTA_GENERAL";
    public static final String AGREGAR_PLANTA_GENERAL = "AGREGAR_PLANTA_GENERAL";
    public static final String MODIFICAR_PLANTA_GENERAL = "MODIFICAR_PLANTA_GENERAL";
    public static final String ELIMINAR_PLANTA_GENERAL = "ELIMINAR_PLANTA_GENERAL";
    public static final String AUDITORIA_ELIMINAR_PLANTA_GENERAL = "AUDITORIA_ELIMINAR_PLANTA_GENERAL";
    public static final String AGREGAR_PERSONAL_PLANTA_GENERAL = "AGREGAR_PERSONAL_PLANTA_GENERAL";
    public static final String MODIFICAR_PERSONAL_PLANTA_GENERAL = "MODIFICAR_PERSONAL_PLANTA_GENERAL";
    public static final String ELIMINAR_PERSONAL_PLANTA_GENERAL = "ELIMINAR_PERSONAL_PLANTA_GENERAL";
    public static final String CARGAR_SELECCIONAR_AUTORIDAD_SUPERIOR = "CARGAR_SELECCIONAR_AUTORIDAD_SUPERIOR";
    public static final String CARGAR_SELECCIONAR_PLANTA_GENERAL = "CARGAR_SELECCIONAR_PLANTA_GENERAL";
    
    //TiposCargoPlantaGeneral
    public static final String OBTENER_TIPOS_CARGOS_PLANTA_GENERAL = "OBTENER_TIPOS_CARGOS_PLANTA_GENERAL";
    
    //PersonalPlantaGeneral
    public static final String OBTENER_CANTIDAD_PERSONAL_PLANTA_GENERAL = "OBTENER_CANTIDAD_PERSONAL_PLANTA_GENERAL";
    public static final String CARGAR_PERSONAL_PLANTA_GENERAL = "CARGAR_PERSONAL_PLANTA_GENERAL";
    public static final String OBTENER_CANTIDAD_PERSONAL_PLANTA_GENERAL_X_CARGO = "OBTENER_CANTIDAD_PERSONAL_PLANTA_GENERAL_X_CARGO";
    public static final String CARGAR_PERSONAL_PLANTA_GENERAL_X_CARGO = "CARGAR_PERSONAL_PLANTA_GENERAL_X_CARGO";
    public static final String OBTENER_PERSONA_PLANTA_GENERAL = "OBTENER_PERSONA_PLANTA_GENERAL";
    public static final String OBTENER_IDS_ELIMINAR_PERSONA_PLANTA_GENERAL = "OBTENER_IDS_ELIMINAR_PERSONA_PLANTA_GENERAL";
    public static final String AGREGAR_PERSONA_PLANTA_GENERAL = "AGREGAR_PERSONA_PLANTA_GENERAL";
    public static final String MODIFICAR_PERSONA_PLANTA_GENERAL = "MODIFICAR_PERSONA_PLANTA_GENERAL";
    public static final String ELIMINAR_PERSONA_PLANTA_GENERAL = "ELIMINAR_PERSONA_PLANTA_GENERAL";
    public static final String AUDITORIA_ELIMINAR_PERSONA_PLANTA_GENERAL = "AUDITORIA_ELIMINAR_PERSONA_PLANTA_GENERAL";
    public static final String OBTENER_CANTIDAD_TOTAL_PERSONAL = "OBTENER_CANTIDAD_TOTAL_PERSONAL";
    public static final String OBTENER_PERSONAL_TOTAL = "OBTENER_PERSONAL_TOTAL";
    
    //TiposProducto
    public static final String OBTENER_TIPOS_PRODUCTO = "OBTENER_TIPOS_PRODUCTO";
    
    //LineaGeneral
    public static final String OBTENER_CANTIDAD_LINEAS_GENERAL = "OBTENER_CANTIDAD_LINEAS_GENERAL";
    public static final String OBTENER_CANTIDAD_LINEAS_GENERAL_IDS_OMITIDOS = "OBTENER_CANTIDAD_LINEAS_GENERAL_IDS_OMITIDOS";
    public static final String OBTENER_LINEAS_GENERAL_X_PLANTA = "OBTENER_LINEAS_GENERAL_X_PLANTA";
    public static final String OBTENER_LINEAS_GENERAL_X_PLANTA_IDS_OMITIDOS = "OBTENER_LINEAS_GENERAL_X_PLANTA_IDS_OMITIDOS";
    public static final String OBTENER_LINEA_GENERAL = "OBTENER_LINEA_GENERAL";
    public static final String AGREGAR_LINEA_GENERAL = "AGREGAR_LINEA_GENERAL";
    public static final String MODIFICAR_LINEA_GENERAL = "MODIFICAR_LINEA_GENERAL";
    public static final String ELIMINAR_LINEA_GENERAL = "ELIMINAR_LINEA_GENERAL";
    public static final String AUDITORIA_ELIMINAR_LINEA_GENERAL = "AUDITORIA_ELIMINAR_LINEA_GENERAL";
    public static final String CARGAR_SELECCIONAR_LINEAS_GENERAL_X_PLANTA_IDS_OMITIDOS = "CARGAR_SELECCIONAR_LINEAS_GENERAL_X_PLANTA_IDS_OMITIDOS";
    
    //CategoriaProducto
    public static final String OBTENER_CATEGORIAS_PRODUCTO = "OBTENER_CATEGORIAS_PRODUCTO";
    
    //MaquinaGeneral
    public static final String OBTENER_CANTIDAD_MAQUINAS_GENERAL = "OBTENER_CANTIDAD_MAQUINAS_GENERAL";
    public static final String OBTENER_MAQUINAS_GENERAL_X_PLANTA = "OBTENER_MAQUINAS_GENERAL_X_PLANTA";
    public static final String OBTENER_MAQUINA_GENERAL = "OBTENER_MAQUINA_GENERAL";
    public static final String OBTENER_LINEAS_GENERAL_ASOCIADAS_MAQUINA_GENERAL = "OBTENER_LINEAS_GENERAL_ASOCIADAS_MAQUINA_GENERAL";
    public static final String AGREGAR_MAQUINA_GENERAL = "AGREGAR_MAQUINA_GENERAL";
    public static final String ASOCIAR_LINEA_GENERAL_A_MAQUINA_GENERAL = "ASOCIAR_LINEA_GENERAL_A_MAQUINA_GENERAL";
    public static final String MODIFICAR_MAQUINA_GENERAL = "MODIFICAR_MAQUINA_GENERAL";
    public static final String ELIMINAR_MAQUINA_GENERAL = "ELIMINAR_MAQUINA_GENERAL";
    public static final String ELIMINAR_LINEA_GENERAL_ASOCIADAS_MAQUINA_GENERAL = "ELIMINAR_LINEA_GENERAL_ASOCIADAS_MAQUINA_GENERAL";
    public static final String AUDITORIA_ELIMINAR_MAQUINA_GENERAL = "AUDITORIA_ELIMINAR_MAQUINA_GENERAL";
    
    //Proveedor General
    public static final String OBTENER_CANTIDAD_PROVEEDORES = "OBTENER_CANTIDAD_PROVEEDORES";
    public static final String OBTENER_PROVEEDORES = "OBTENER_PROVEEDORES";
    public static final String OBTENER_PROVEEDOR_GENERAL = "OBTENER_PROVEEDOR_GENERAL";
    public static final String AGREGAR_PROVEEDOR_GENERAL = "AGREGAR_PROVEEDOR_GENERAL";
    public static final String AUDITORIA_ELIMINAR_PROVEEDOR_GENERAL = "AUDITORIA_ELIMINAR_PROVEEDOR_GENERAL";
    public static final String ELIMINAR_PROVEEDOR_GENERAL = "ELIMINAR_PROVEEDOR_GENERAL";
    public static final String MODIFICAR_PROVEEDOR_GENERAL = "MODIFICAR_PROVEEDOR_GENERAL";
    
    //ProductoProveedor
    public static final String OBTENER_CANTIDAD_PRODUCTOS_PROVEEDOR = "OBTENER_CANTIDAD_PRODUCTOS_PROVEEDOR";
    public static final String OBTENER_PRODUCTOS_PROVEEDOR = "OBTENER_PRODUCTOS_PROVEEDOR";
    public static final String OBTENER_PRODUCTO_PROVEEDOR = "OBTENER_PRODUCTO_PROVEEDOR";
    public static final String AGREGAR_PRODUCTO_PROVEEDOR = "AGREGAR_PRODUCTO_PROVEEDOR";
    public static final String AUDITORIA_ELIMINAR_PRODUCTO_PROVEEDOR = "AUDITORIA_ELIMINAR_PRODUCTO_PROVEEDOR";
    public static final String ELIMINAR_PRODUCTO_PROVEEDOR = "ELIMINAR_PRODUCTO_PROVEEDOR";
    public static final String MODIFICAR_PRODUCTO_PROVEEDOR = "MODIFICAR_PRODUCTO_PROVEEDOR";
    
    //SucursalProveedor
    public static final String OBTENER_CANTIDAD_SUCURSALES_PROVEEDOR = "OBTENER_CANTIDAD_SUCURSALES_PROVEEDOR";
    public static final String OBTENER_SUCURSALES_PROVEEDOR = "OBTENER_SUCURSALES_PROVEEDOR";
    public static final String OBTENER_SUCURSAL_PROVEEDOR = "OBTENER_SUCURSAL_PROVEEDOR";
    public static final String AGREGAR_SUCURSAL_PROVEEDOR = "AGREGAR_SUCURSAL_PROVEEDOR";
    public static final String AUDITORIA_ELIMINAR_SUCURSAL_PROVEEDOR = "AUDITORIA_ELIMINAR_SUCURSAL_PROVEEDOR";
    public static final String ELIMINAR_SUCURSAL_PROVEEDOR = "ELIMINAR_SUCURSAL_PROVEEDOR";
    public static final String MODIFICAR_SUCURSAL_PROVEEDOR = "MODIFICAR_SUCURSAL_PROVEEDOR";
    
    //ProductoSucursal
    public static final String OBTENER_CANTIDAD_PRODUCTOS_SUCURSAL = "OBTENER_CANTIDAD_PRODUCTOS_SUCURSAL";
    public static final String OBTENER_PRODUCTOS_SUCURSAL = "OBTENER_PRODUCTOS_SUCURSAL";
    public static final String OBTENER_PRODUCTO_SUCURSAL = "OBTENER_PRODUCTO_SUCURSAL";
    public static final String AGREGAR_PRODUCTO_SUCURSAL = "AGREGAR_PRODUCTO_SUCURSAL";
    public static final String AUDITORIA_ELIMINAR_PRODUCTO_SUCURSAL = "AUDITORIA_ELIMINAR_PRODUCTO_SUCURSAL";
    public static final String ELIMINAR_PRODUCTO_SUCURSAL = "ELIMINAR_PRODUCTO_SUCURSAL";
    public static final String OBTENER_CANTIDAD_PRODUCTOS_SUCURSAL_FALTANTES = "OBTENER_CANTIDAD_PRODUCTOS_SUCURSAL_FALTANTES";
    public static final String OBTENER_PRODUCTOS_SUCURSAL_FALTANTES = "OBTENER_PRODUCTOS_SUCURSAL_FALTANTES";
    
    //CategoriaEquipoMedicion
    public static final String OBTENER_CATEGORIAS_EQUIPO_MEDICION = "OBTENER_CATEGORIAS_EQUIPO_MEDICION";    
    
    //EquipoMedicion
    public static final String OBTENER_CANTIDAD_EQUIPOS_MEDICION = "OBTENER_CANTIDAD_EQUIPOS_MEDICION";
    public static final String OBTENER_EQUIPOS_MEDICION = "OBTENER_EQUIPOS_MEDICION";
    public static final String OBTENER_EQUIPOS_MEDICION_AUXILIARES = "OBTENER_EQUIPOS_MEDICION_AUXILIARES";
    public static final String OBTENER_EQUIPO_MEDICION = "OBTENER_EQUIPO_MEDICION";
    public static final String AGREGAR_EQUIPO_MEDICION = "AGREGAR_EQUIPO_MEDICION";
    public static final String AUDITORIA_ELIMINAR_EQUIPO_MEDICION = "AUDITORIA_ELIMINAR_EQUIPO_MEDICION";
    public static final String ELIMINAR_EQUIPO_MEDICION = "ELIMINAR_EQUIPO_MEDICION";
    public static final String MODIFICAR_EQUIPO_MEDICION = "MODIFICAR_EQUIPO_MEDICION";    
    
    //FactorAmbiente
    public static final String OBTENER_FACTORES_AMBIENTE = "OBTENER_FACTORES_AMBIENTE";
    
    //AreaEnsayo
    public static final String OBTENER_AREAS_ENSAYO = "OBTENER_AREAS_ENSAYO";
    
    //CondicionAmbiental
    public static final String OBTENER_CANTIDAD_CONDICIONES_AMBIENTALES = "OBTENER_CANTIDAD_CONDICIONES_AMBIENTALES";
    public static final String OBTENER_CONDICIONES_AMBIENTALES = "OBTENER_CONDICIONES_AMBIENTALES";
    public static final String OBTENER_CONDICION_AMBIENTAL = "OBTENER_CONDICION_AMBIENTAL";
    public static final String AGREGAR_CONDICION_AMBIENTAL = "AGREGAR_CONDICION_AMBIENTAL";
    public static final String AUDITORIA_ELIMINAR_CONDICION_AMBIENTAL = "AUDITORIA_ELIMINAR_CONDICION_AMBIENTAL";
    public static final String ELIMINAR_CONDICION_AMBIENTAL = "ELIMINAR_CONDICION_AMBIENTAL";
    public static final String MODIFICAR_CONDICION_AMBIENTAL = "MODIFICAR_CONDICION_AMBIENTAL";
    
    //GrupoProductoGeneral
    public static final String OBTENER_CANTIDAD_GRUPOS_PRODUCTO_GENERAL = "OBTENER_CANTIDAD_GRUPOS_PRODUCTO_GENERAL";
    public static final String OBTENER_GRUPOS_PRODUCTO_GENERAL_X_LINEA = "OBTENER_GRUPOS_PRODUCTO_GENERAL_X_LINEA";
    public static final String OBTENER_GRUPO_PRODUCTO_GENERAL = "OBTENER_GRUPO_PRODUCTO_GENERAL";
    public static final String AGREGAR_GRUPO_PRODUCTO_GENERAL = "AGREGAR_GRUPO_PRODUCTO_GENERAL";
    public static final String AUDITORIA_ELIMINAR_GRUPO_PRODUCTO_GENERAL = "AUDITORIA_ELIMINAR_GRUPO_PRODUCTO_GENERAL";
    public static final String ELIMINAR_GRUPO_PRODUCTO_GENERAL = "ELIMINAR_GRUPO_PRODUCTO_GENERAL";
    public static final String MODIFICAR_GRUPO_PRODUCTO_GENERAL = "MODIFICAR_GRUPO_PRODUCTO_GENERAL";
    
    //EstadoProcesoProducto
    public static final String OBTENER_ESTADOS_PROCESO_PRODUCTO = "OBTENER_ESTADOS_PROCESO_PRODUCTO";
    
    //ProductoGeneral
    public static final String OBTENER_CANTIDAD_PRODUCTOS_GENERAL_PADRES = "OBTENER_CANTIDAD_PRODUCTOS_GENERAL_PADRES";
    public static final String OBTENER_PRODUCTOS_GENERAL_PADRES_X_GRUPO = "OBTENER_PRODUCTOS_GENERAL_PADRES_X_GRUPO";
    public static final String OBTENER_CANTIDAD_PRODUCTOS_GENERAL_HIJOS = "OBTENER_CANTIDAD_PRODUCTOS_GENERAL_HIJOS";
    public static final String OBTENER_PRODUCTOS_GENERAL_HIJOS = "OBTENER_PRODUCTOS_GENERAL_HIJOS";
    public static final String OBTENER_PRODUCTO_GENERAL = "OBTENER_PRODUCTO_GENERAL";
    public static final String AGREGAR_PRODUCTO_GENERAL = "AGREGAR_PRODUCTO_GENERAL";
    public static final String AUDITORIA_ELIMINAR_PRODUCTO_GENERAL = "AUDITORIA_ELIMINAR_PRODUCTO_GENERAL";
    public static final String ELIMINAR_PRODUCTO_GENERAL = "ELIMINAR_PRODUCTO_GENERAL";
    public static final String MODIFICAR_PRODUCTO_GENERAL = "MODIFICAR_PRODUCTO_GENERAL";    
    
    // </editor-fold> 
        
    
    //PROPERTIES
    public static final String OBTENER_PROPERTIES_PARAMETROS = "OBTENER_PROPERTIES_PARAMETROS";
    public static final String OBTENER_PROPERTIES_ENDPOINTS = "OBTENER_PROPERTIES_ENDPOINTS";
    
    //OTROS
    public static final String SERVLET_INICIAL = "SERVLET_INICIAL";
    public static final String SERVLET_FILTRO = "SERVLET_FILTRO";
    public static final String RESPUESTA_SERVLET = "RESPUESTA_SERVLET";
    public static final String CERRAR_SESSION = "CERRAR_SESSION";
    public static final String MODAL_VER = "MODAL_VER";
    public static final String MODAL_AGREGAR = "MODAL_AGREGAR";
    public static final String MODAL_MODIFICAR = "MODAL_MODIFICAR";
    public static final String MODAL_REPORTE = "MODAL_REPORTE";
    public static final String MODAL_SELECCIONAR = "MODAL_SELECCIONAR";
    public static final String MOSTRAR_PANTALLA = "MOSTRAR_PANTALLA";
    public static final String MOSTRAR_SECCION = "MOSTRAR_SECCION";
    public static final String OCULTAR_SECCION = "OCULTAR_SECCION";
    
}
